### ISSUE TITLE
[Docs]: FSxN is reported as unsupported and supported at the same time

### ISSUE THREAD

**Issue by hananstrul** [NetApp/terraform-provider-netapp-ontap#330]
### Documentation Link

https://registry.terraform.io/providers/NetApp/netapp-ontap/latest/docs/resources/snapmirror_resource

### Description

Please look at the supported platforms list below and the opposite support message
Please fix and remove the note section

![image](https://github.com/user-attachments/assets/2a7f88de-bc7b-4783-b072-a5d7ce38e08b)

### Would you like to implement a fix?

None

**Comment by chuyich** [comment]
It has been taken care in the next release.
