### ISSUE TITLE
[New Data Source]: /storage/qos/policies

### ISSUE THREAD

**Issue by carchi8py** [NetApp/terraform-provider-netapp-ontap#77]
### Description

Ability to get QOS data

### Requested Resource(s) and/or Data Source(s)

* netapp_ontap_storage_qos_policies

### References

https://library.netapp.com/ecmdocs/ECMLP2885799/html/#/storage/qos_policy_collection_get

### Would you like to implement a fix?

None

**Comment by xlai89** [comment]
Hi, may I work on this data source? I have some experience working with the NetApp Terraform provider, and I'm eager to start contributing to open source projects, starting with this one.
