### ISSUE TITLE
[New Data Source]: /storage/qtrees

### ISSUE THREAD

**Issue by carchi8py** [NetApp/terraform-provider-netapp-ontap#83]
### Description

ability to get info on qtrees

### Requested Resource(s) and/or Data Source(s)

* netapp_ontap_storage_qtrees

### References

https://library.netapp.com/ecmdocs/ECMLP2885799/html/#/storage/qtree_collection_get

### Would you like to implement a fix?

None

**Comment by wenjun666** [comment]
Completed along with resources PR.
